"""Tests for aipr policy detection."""

from aipr.detector import Verdict, detect_policy


HUMAN_ONLY = """
# Contributing

## AI Policy
All AI usage in any form must be disclosed.
AI should never be the main author of the PR. Issues and PR descriptions must
be fully human-written. Bad AI drivers will be denounced.
"""

DISCLOSE_OK = """
# Contributing
AI-assisted contributions are welcome as long as they are disclosed.
Add the `Assisted-by: AI` trailer to your commits.
"""

PERMISSIVE = """
# Contributing
We warmly welcome AI-assisted contributions. Feel free to use Claude, Copilot,
ChatGPT or any LLM tooling - just stand by the code you ship. Agents are welcome.
"""

SILENT = """# Contributing

Thanks for your interest! Fork, hack, open a PR. We use ruff and pytest.
"""


def test_human_only_detected():
    p = detect_policy(HUMAN_ONLY)
    assert p.verdict is Verdict.HUMAN_ONLY
    assert p.autonomous_safe is False
    assert any("never be the main author" in e for e in p.evidence)


def test_disclose_ok_detected():
    p = detect_policy(DISCLOSE_OK)
    # "welcome as long as disclosed" reads as permissive-with-terms; either
    # permissive or disclose_ok is acceptable, both are autonomous-safe.
    assert p.verdict in (Verdict.DISCLOSE_OK, Verdict.PERMISSIVE)
    assert p.autonomous_safe is True
    assert p.score < 0


def test_permissive_detected():
    p = detect_policy(PERMISSIVE)
    assert p.verdict is Verdict.PERMISSIVE
    assert p.autonomous_safe is True


def test_silent_is_unknown():
    p = detect_policy(SILENT)
    assert p.verdict is Verdict.UNKNOWN
    assert p.confidence == 0.0
    assert p.autonomous_safe is False


def test_empty_text():
    p = detect_policy("")
    assert p.verdict is Verdict.UNKNOWN


def test_restrictive_beats_weak_permissive():
    # disclosure requirement (+2.5) outweighs the trailer mention (-1.5)
    mixed = (
        "All AI usage in any form must be disclosed. "
        "Add the Assisted-by: AI trailer.\n"
    )
    p = detect_policy(mixed)
    assert p.verdict is Verdict.RESTRICTIVE
    assert p.autonomous_safe is False


def test_evidence_always_present_when_not_unknown():
    for text in (HUMAN_ONLY, DISCLOSE_OK, PERMISSIVE):
        p = detect_policy(text)
        assert p.evidence, "expected at least one evidence snippet"


def test_verdicts_are_distinct():
    values = {v.value for v in Verdict}
    assert {"human_only", "restrictive", "disclose_ok", "permissive", "unknown"} <= values

OPENHUMAN_GUIDE = """
## Optional — Let an AI coding agent guide you
If you use Claude Code, Cursor, AmpCode, Codex, or another coding agent, you can paste this prompt after cloning the repo:
AGENTS.md: https://raw.githubusercontent.com/tinyhumansai/openhuman/main/AGENTS.md
CLAUDE.md: https://raw.githubusercontent.com/tinyhumansai/openhuman/main/CLAUDE.md
"""

def test_openhuman_agent_guide_is_permissive():
    p = detect_policy(OPENHUMAN_GUIDE)
    assert p.verdict is Verdict.PERMISSIVE
    assert p.autonomous_safe is True
    assert p.score <= -3.0


UNDERSTANDING_MANDATE = """
# Agent Guidelines

You must disclose in your initial issue or pull request that you used AI/LLM, as well as the tools/models you used.
You should understand every line of code written by AI and know what the AI did.
You must review all code, text, and other content generated by AI/LLM yourself before proactively requesting a review from any member.
You must not attribute commits to AI/LLM, including through "Assisted-by", "Co-developed-by", or similar trailers.
If you are unwilling or unable to do all of the above, please close your issue or pull request.
"""


def test_understanding_mandate_is_human_only():
    p = detect_policy(UNDERSTANDING_MANDATE)
    assert p.verdict is Verdict.HUMAN_ONLY
    assert p.autonomous_safe is False
    assert p.score >= 4.0


def test_alibaba_agents_md_classifies_correctly():
    """Real AGENTS.md from alibaba/open-code-review: requires disclosure,
    understanding, no AI attribution — should be HUMAN_ONLY."""
    p = detect_policy(UNDERSTANDING_MANDATE)
    assert p.verdict is Verdict.HUMAN_ONLY


def test_detect_policy_lru_cache():
    from aipr.detector import clear_policy_cache
    clear_policy_cache()
    
    sample = "# Contributing\n\nWe warmly welcome AI-assisted contributions. Agents are welcome."
    p1 = detect_policy(sample)
    p2 = detect_policy(sample)
    assert p1 == p2, "Expected equal Policy objects from LRU cache (deep copy semantics)"
    
    clear_policy_cache()
    p3 = detect_policy(sample)
    assert p3 == p1
    assert p3 is not p1, "Expected cache_clear to force re-evaluation"


CURSORRULES_RESTRICTIVE = """
# Cursor Rules

Never generate code for files in src/legacy/ without human review.
"""


def test_cursorrules_restrictive_detected():
    p = detect_policy(CURSORRULES_RESTRICTIVE)
    assert p.verdict is Verdict.RESTRICTIVE
    assert p.autonomous_safe is False
    assert any("Never generate code for" in e for e in p.evidence)


def test_local_policy_restrictive_patterns():
    # all changes must be reviewed
    p1 = detect_policy("All changes must be reviewed before merging.")
    assert p1.verdict is Verdict.RESTRICTIVE
    assert p1.autonomous_safe is False

    # all edits must be human reviewed
    p2 = detect_policy("All edits must be human-reviewed.")
    assert p2.verdict is Verdict.RESTRICTIVE
    assert p2.autonomous_safe is False

    # do not use copilot / cursor / aider for
    p3 = detect_policy("Do not use Copilot for security-critical modules.")
    assert p3.verdict is Verdict.RESTRICTIVE
    assert p3.autonomous_safe is False

    p4 = detect_policy("Do not use cursor to modify database schemas.")
    assert p4.verdict is Verdict.RESTRICTIVE
    assert p4.autonomous_safe is False

    p5 = detect_policy("Never use aider for documentation.")
    assert p5.verdict is Verdict.RESTRICTIVE
    assert p5.autonomous_safe is False


def test_ordinary_ai_mention_not_restrictive():
    sample = "This project uses Cursor, Windsurf, Copilot, and Aider as development tools."
    p = detect_policy(sample)
    assert p.verdict is Verdict.UNKNOWN
    assert p.autonomous_safe is False
    assert p.score == 0.0
